project:
  type: website
  output-dir: docs

website:
  title: "SOS Plan de Estabilización"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre nosotros

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



