project:
  type: website
  output-dir: docs

website:
  navbar:
    logo: "sos_plan.png"
    logo-alt: "SOS Plan de Estabilización"
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre nosotros

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto


